dataset: mit-states
clip_model: ViT-L/14
seed: 0
epochs: 50
lr: 0.00005
loss: GenCSPLoss
attr_dropout: 0.3
weight_decay: 0.00002
train_batch_size: 64
eval_batch_size: 64
gradient_accumulation_steps: 2
best_model_metric: AUC
context_length: 8
text_db: 'opt_sentences64_all_pairs_open.pkl'
num_texts: 64
num_aug: 8
attn_dropout: 0.5
use_gauss: True
with_group: True
disentangle: True
fusion: True
fusion_factor: beta
use_attrobj_gauss: True
w_attr: 0.1
w_obj: 0.1
save_path: output/mit-states/fullmodel
save_every_n: 2
num_workers: 4
pin_memory: True